package com.ipasssdk.model.response

class SocialAccountDetailData {

    var apple = SocialAccountRegistrationData()
    var ebay = SocialAccountRegistrationData()
    var facebook = SocialAccountRegistrationData()
    var flickr = SocialAccountRegistrationData()
    var foursquare = SocialAccountRegistrationData()
    var github = SocialAccountRegistrationData()
    var google = SocialAccountRegistrationData()
    var gravatar = SocialAccountRegistrationData()
    var instagram = SocialAccountRegistrationData()
    var lastfm = SocialAccountRegistrationData()
    var linkedin = SocialAccountRegistrationData()
    var microsoft = SocialAccountRegistrationData()
    var myspace = SocialAccountRegistrationData()
    var pinterest = SocialAccountRegistrationData()
    var skype = SocialAccountRegistrationData()
    var spotify = SocialAccountRegistrationData()
    var tumblr = SocialAccountRegistrationData()
    var twitter = SocialAccountRegistrationData()
    var vimeo = SocialAccountRegistrationData()
    var weibo = SocialAccountRegistrationData()
    var yahoo = SocialAccountRegistrationData()
    var discord = SocialAccountRegistrationData()
    var ok = SocialAccountRegistrationData()
    var kakao = SocialAccountRegistrationData()
    var booking = SocialAccountRegistrationData()
    var airbnb = SocialAccountRegistrationData()
    var amazon = SocialAccountRegistrationData()
    var qzone = SocialAccountRegistrationData()
    var adobe = SocialAccountRegistrationData()
    var mailru = SocialAccountRegistrationData()
    var wordpress = SocialAccountRegistrationData()
    var imgur = SocialAccountRegistrationData()
    var disneyplus = SocialAccountRegistrationData()
    var netflix = SocialAccountRegistrationData()
    var jdid = SocialAccountRegistrationData()
    var flipkart = SocialAccountRegistrationData()
    var bukalapak = SocialAccountRegistrationData()
    var archiveorg = SocialAccountRegistrationData()
    var lazada = SocialAccountRegistrationData()
    var zoho = SocialAccountRegistrationData()
    var samsung = SocialAccountRegistrationData()
    var evernote = SocialAccountRegistrationData()
    var envato = SocialAccountRegistrationData()
    var patreon = SocialAccountRegistrationData()
    var tokopedia = SocialAccountRegistrationData()
    var rambler = SocialAccountRegistrationData()
    var quora = SocialAccountRegistrationData()
    var atlassian = SocialAccountRegistrationData()
    var snapchat = SocialAccountRegistrationData()
    var whatsapp = SocialAccountRegistrationData()
    var telegram = SocialAccountRegistrationData()
    var viber = SocialAccountRegistrationData()
    var zalo = SocialAccountRegistrationData()
    var line = SocialAccountRegistrationData()


}